### ISSUE TITLE
Location Identifier changes: New airport in Istanbul, Turkey

### ISSUE THREAD

**Issue by btafarelo** [opentraveldata/opentraveldata#112]
Hi.

I have detected this iatas exchange.

FROM:
ISL - Istanbul New Airport
IST - Istanbul Ataturk Airport

TO:
IST - Istanbul New Airport
ISL - Istanbul Ataturk Airport

https://www.iata.org/policy/slots/Documents/slot_news/2018%20April%20news/iata-spec-ind-notif-ist.pdf

If you need something else, please let me know.

Regards

**Comment by denisarnaud** [comment]
Thanks for your contribution!

Note that there must exist other notifications from IATA, and/or some errata, because IST has always been assigned to the old airport, and is still is, and ISL has been assigned to the new airport.
See for instance https://www.iata.org/publications/Pages/code-search.aspx
Wikipedia also gets it right:
* https://en.wikipedia.org/wiki/Istanbul_New_Airport (IATA: ISL)
* https://en.wikipedia.org/wiki/Istanbul_Atat%C3%BCrk_Airport (IATA: IST)
