### ISSUE TITLE
QZX airport not found

### ISSUE THREAD

**Issue by alexprengere** [opentraveldata/opentraveldata#113]
We have been seeing errors related to [QZX](https://www.icao.int/safety/RunwaySafety/Lists/Airport%20Movements/DispForm.aspx?ID=3570&ContentTypeId=0x0100E70F02AC22B6AB4A8883977CCB92D964), but I am not completely sure it exists.

**Comment by leomrocha** [comment]
What seems strange is: https://www.icao.int/safety/RunwaySafety/Lists/Airport%20Movements/DispForm.aspx?ID=3570&ContentTypeId=0x0100E70F02AC22B6AB4A8883977CCB92D964
But somebody says that it nows belong to UBG https://www.flyertalk.com/forum/oneworld/364131-qzx-unknown-destination.html

Nevertheless is a strange thing

**Comment by denisarnaud** [comment]
It is a fictitious point. One use case is for airlines to mask the actual destination of their flights (so-called mystery flights). Another use case is to represent generic destinations, for instance some station on the railway network.
So, depending on the airline using that fictitious point, it can be located anywhere. According to ICAO, that specific one is in South Africa. Though I guess that nothing is binding here, since we are talking about fictitious points.
