### ISSUE TITLE
Entries to be made in the OPTD POR public file

### ISSUE THREAD

**Issue by deepak0000** [opentraveldata/opentraveldata#135]
Hello,

Please could you add the following entries in the OPTD POR public file?
HKMM - Migori Airport -> https://www.greatcirclemapper.net/en/airport/HKMM-migori-airport.html
WAOM - Beringin Airport -> https://www.world-airport-codes.com/indonesia/municipal-4455.html
WITG - Lasikin Airport -> https://www.world-airport-codes.com/indonesia/lasikin-84347.html
WRLM - Malinau Airport -> https://www.greatcirclemapper.net/en/airport/WRLM-malinau-airport.html
WRLE - West Kutai Melalan Airport -> https://en.wikipedia.org/wiki/West_Kutai_Melalan_Airport: Please update an entry to include the WRLE code

Best,
Deepak

**Comment by denisarnaud** [comment]
Thanks for your contributions Deepak!

Note that (at least) the first one on the list is already in OPTD. As it has no IATA code, it is not in the [`opentraveldata/optd_por_public.csv` file](https://github.com/opentraveldata/opentraveldata/blob/master/opentraveldata/optd_por_public.csv), which by design contains only POR having been assigned a IATA code at some point in time.
Rather, it is in the [`pentraveldata/optd_por_public_all.csv` file](https://github.com/opentraveldata/opentraveldata/blob/master/opentraveldata/optd_por_public_all.csv):
```txt
iata_code^icao_code^faa_code^is_geonames^geoname_id^envelope_id^name^asciiname^latitude^longitude^fclass^fcode^page_rank^date_from^date_until^comment^country_code^cc2^country_name^continent_name^adm1_code^adm1_name_utf^adm1_name_ascii^adm
2_code^adm2_name_utf^adm2_name_ascii^adm3_code^adm4_code^population^elevation^gtopo30^timezone^gmt_offset^dst_offset^raw_offset^moddate^city_code_list^city_name_list^city_detail_list^tvl_por_list^iso31662^location_type^wiki_link^alt_name_
section^wac^wac_name^ccy_code^unlc_list^uic_list
^HKMM^^Y^11395447^^Migori Airport^Migori Airport^-1.11564^34.48514^S^AIRP^^^^^KE^^Kenya^Africa^36^Migori^Migori^^^^^^0^^1407^Africa/Nairobi^3.0^3.0^3.0^2016-12-10^^^^^^A^^en|Migori Airport|^535^Kenya^KES^^
```

No Wikipedia page seems to exist yet. So, feel free to create one, for instance taking inspiration from [other small airports in Kenya (KE)](https://en.wikipedia.org/wiki/List_of_airports_in_Kenya), such as [Bamburi Airport](https://en.wikipedia.org/wiki/Bamburi_Airport) for instance.

**Comment by denisarnaud** [comment]
The second POR in the list (with ICAO code HKMM) is also in OPTD. It has a IATA code, namely GXA:
* [Muara Teweh Beringin Airport in Geonames](https://www.geonames.org/8531905)
* [Muara Teweh Beringin Airport in Wikipedia](https://en.wikipedia.org/wiki/Beringin_Airport)

**Comment by denisarnaud** [comment]
The third POR in the list (with ICAO code WITG) is also in OPTD. It has no IATA code:
* [Lasikin Airport in Geonames](https://www.geonames.org/8533855)
* [Lasikin Airport in Wikipedia](https://en.wikipedia.org/wiki/Lasikin_Airport)

**Comment by denisarnaud** [comment]
For the fourth and fifth records on the list above (WALE/WRLE and WALM/WRLM), entries have been added in the [`opentraveldata/optd_por_no_longer_valid.csv` file](https://github.com/opentraveldata/opentraveldata/blob/master/opentraveldata/optd_por_no_longer_valid.csv) with the old ICAO codes (and without IATA codes, as those airports had no IATA code before), _i.e._, respectively WRLE and WRLM. The entries with the new ICAO codes (respectively WALE and WALE) were already in OPTD.
