### ISSUE TITLE
Change airport TSE -> NQZ

### ISSUE THREAD

**Issue by fisichel** [opentraveldata/opentraveldata#159]
Hi team and thank you for your work ;)
Could you please take a look at this particular airport TSE / NQZ :
https://fr.wikipedia.org/wiki/A%C3%A9roport_international_Noursoultan-Nazarba%C3%AFev
It looks like TSE has been replaced by NQZ, and might be worth adding to the airports list.
Cheers !

**Comment by denisarnaud** [comment]
Thanks @fisichel !

Note that NQZ has already been the active IATA code for https://en.wikipedia.org/wiki/Nursultan_Nazarbayev_International_Airport since June 2020. For instance:
* On Travel Search: https://www.transport-search.org/?q=nqz
* On Geonames: https://www.geonames.org/6300914/astana-nursultan-nazarbayev-international-airport.html

On the other hand, TSE has been deprecated, and kept in the records for archive purpose only.
