### ISSUE TITLE
Duplicate city codes - which one is relevant?

### ISSUE THREAD

**Issue by tadhgpearson** [opentraveldata/opentraveldata#32]
I have noticed that in `opentraveldata/optd_por_public.csv` there are some duplicate IATA codes for the same `location_type`. 

For example: `AAJ` is referenced twice, on lines 20 and 21, with different names. Both have `location_type` C(=city), but different GeoNames IDs. Nearly all of the remaining properties are the same. 

Which one should I keep? Is there some way to help me determine which one to keep?

More widely, is there any way to filter the file so I can get a unique key based on IATA code + location_type + some other column?

**Comment by tadhgpearson** [comment]
Here's a better example - `EWR` on lines 1072 / 4073
Travel agents will tell you that EWR is the city code for N**EW**a**R**k NJ - see, for example, on [airportcod.es](http://airportcod.es/#airport/ewr)
In the POR file, we have the choice of Iselin and Newark - and while I don't doubt that theoretically both cities could apply to this code, if you had to select just one, you would select Newark. Is there any way to automate this decision based on the data provided?

**Comment by denisarnaud** [comment]
See also #12

**Comment by tadhgpearson** [comment]
Thanks for the detailed explanation Denis.

Regarding your last questions - I don't think it's hard to pick the most common implementation in these examples.

You can Google it. For example: Google _EWR Iselin_, and you will get 32k results. Google _EWR Newark_, you will get 10M. Similarly, _AAJ Cajana_ gives 164k results, _AAJ "Awa Dam"_ gives just 137 results.

Similarly, I guess I could use a word distance score perhaps, to see if more letters of the IATA code exists as a proportion of one name to another. That would work in these two examples, I don't know how it would scale.

It would be better to use signals in the file I could use to select the correct option systematically. Are they any you would suggest?

**Comment by denisarnaud** [comment]
You could use your idea of doing a Google search of "<IATA code> <city name>", potentially through the Google search API. That way, we wouldn't have to add anything to OpenTravelData. Because, again, it is a matter of choice. Here, as Iselin is the official city referenced by IATA, some people will want to pick Iselin as the city for EWR. And, in some other cases, Newark will be more natural. So, it is up to every user to choose whatever they prefer.
Adding the Google search popularity, or any other popularity measure, to the optd_por_public.csv file, is doable in theory, but it is not simple to derive/build. The main issue is how to get a popularity/measure for every POR referenced by OpenTravelData. If you come up with some equivalent open/freely accessible data file, we could then make the junction. But, otherwise, it will be difficult.

**Comment by tadhgpearson** [comment]
Thanks Denis.
So, you've made a good point here - Iselin is the official city referenced by IATA, and Newark is referenced from... ? Is there any way to identify the official city that's been referenced by IATA in the data set?

**Comment by tadhgpearson** [comment]
Also - thanks to your answer we identified an important improvement in our APIs.

Some cities (like EWR) are not associated to their airports with the same code. Therefore, when requesting location data for a specific code, we always have to look for the airport and the city in both tables. We can't just assume the airport with the same location code is always referenced from the city

**Comment by denisarnaud** [comment]
> Is there any way to identify the official city that's been referenced by IATA in the data set?

As a matter of fact, with that specific EWR example, IATA references only Iselin as a city. I just added Newark as a city for EWR, because 1) it used to be the case before 2) it makes a lot of sense!

Note, though, that IATA may reference several distinct cities for the same IATA code. For instance:
- RDU for Raleigh and Durham, North Carolina, United States
- EAP for Basel, Switzerland, and Mulhouse, France. That one is a really convoluted example (nice to test your API)!
