### ISSUE TITLE
Airport lat/lon removed

### ISSUE THREAD

**Issue by vojnovski** [opentraveldata/opentraveldata#72]
It seems that the f2afd3ba1a8b59f59748813095711494bf20627b removed the lat/lon info for GRV airport. Any reason why?

**Comment by denisarnaud** [comment]
Thanks Viktor!

Coordinates "disappear" when the IATA code has moved from one Geonames ID to another, and that the [``opentraveldata/optd_por_best_known_so_far.csv`` file](http://github.com/opentraveldata/opentraveldata/blob/master/opentraveldata/optd_por_best_known_so_far.csv) has not be updated to reflect that change.
It has been fixed with d10057f.

Normally, there is a quality assurance script, namely [``opentraveldata/check-por-geo-id-in-optd.py`` Python script](https://github.com/service-delivery-quality/quality-assurance/blob/master/samples/opentraveldata/check-por-geo-id-in-optd.py), which should detect that kind of issues.
Performing those tests is not automated yet (and the results of those tests are not collected and published). However, do not hesitate to run them, open the corresponding issues, and even fixing them!

As an example of well appreciated contributions, @andk (Andreas König) is helping a lot on curating the [above mentioned file](http://github.com/opentraveldata/opentraveldata/blob/master/opentraveldata/optd_por_best_known_so_far.csv). See for instance #57 (thanks Andreas!).

**Comment by vojnovski** [comment]
Thanks Denis! :)
