### ISSUE TITLE
DMA no longer has lat/lng

### ISSUE THREAD

**Issue by alexprengere** [opentraveldata/opentraveldata#73]
A recent commit has removed the lat/lng of the DMA airport: 32.166467 -110.883144, which looked good to me. I detected this by automatically [testing missing geocodes](https://github.com/alexprengere/neobase/blob/master/test_neobase.py#L57-L65).

**Comment by denisarnaud** [comment]
Thanks Alex!

As a matter of fact, that issue was only temporary and fixed by this morning update: [bc147d3](https://github.com/opentraveldata/opentraveldata/commit/bc147d3c81aeb2a834e4d22a63cea728575208be#diff-bd88c7fade35cd1067313b43ddc241f8L3470)
It happened because the Geonames database was updated after midnight CET, the OpenTravelData and Geonames data were not synchronized, and I missed that error in the numerous daily updates.

Nevertheless, it has been fixed by now. Thanks for the report!

@vojnovski should be interested by your [testing code](https://github.com/alexprengere/neobase/blob/master/test_neobase.py#L57-L65) as well.

**Comment by alexprengere** [comment]
Thanks for the amazing work as usual :wink:.
I should be able to report such errors more quickly now that I have the automated tests.

**Comment by alexprengere** [comment]
Ok so after cheking the latest file, it seems now ATI no longer have geocodes, previously it was -30.42 -56.52.

**Comment by denisarnaud** [comment]
Thanks Alex!
