### ISSUE TITLE
Invalid timezones in latest data

### ISSUE THREAD

**Issue by alexprengere** [opentraveldata/opentraveldata#77]
The latest version of the data contains invalid timezones: NEI (Europe/Russia) and KJT (Asia/Indonesia). 

The second part of the timezone is usually a city. The list of all timezones can be displayed with `pytz`:
```bash
$ python -c "import pytz; print('\n'.join(pytz.all_timezones))"
Africa/Abidjan
Africa/Accra
Africa/Addis_Ababa
Africa/Algiers
Africa/Asmara
Africa/Asmera
...
```

**Comment by denisarnaud** [comment]
Thanks @alexprengere!

Yes, that happens when the POR are unknown from both [OpenTravelData (``opentraveldata/optd_por_best_known_so_far.csv`` CSV file)](http://github.com/opentraveldata/opentraveldata/blob/master/opentraveldata/optd_por_best_known_so_far.csv) and Geonames. A time-zone code is then assigned based only on the country (as seen in the [``opentraveldata/optd_tz_light.csv`` CSV file](http://github.com/opentraveldata/opentraveldata/blob/master/opentraveldata/optd_tz_light.csv)) by the [``tools/extract_non_geonames_por.awk`` AWK script](http://github.com/opentraveldata/opentraveldata/blob/master/tools/extract_non_geonames_por.awk#L268).

As some countries span multiple time-zones, that process may be refined thanks to the [``opentraveldata/optd_por_tz.csv`` CSV file](http://github.com/opentraveldata/opentraveldata/blob/master/opentraveldata/optd_por_tz.csv), as seen in the [``tools/extract_non_geonames_por.awk`` AWK script](http://github.com/opentraveldata/opentraveldata/blob/master/tools/extract_non_geonames_por.awk#L287) again.

But, at that stage, rather than adding an entry to the [``opentraveldata/optd_por_tz.csv`` CSV file](http://github.com/opentraveldata/opentraveldata/blob/master/opentraveldata/optd_por_tz.csv), it is much better to add the POR in Geonames and in [OpenTravelData (``opentraveldata/optd_por_best_known_so_far.csv`` CSV file)](http://github.com/opentraveldata/opentraveldata/blob/master/opentraveldata/optd_por_best_known_so_far.csv)... which I have done for both the POR you mentioned above :)
So, the issue should have been fixed.

Could you please give the script which you have run in order to find out that issue?

Also, please do not hesitate to contribute to the [Service Delivery Quality (SDQ) project](http://github.com/service-delivery-quality/quality-assurance/tree/master/samples/opentraveldata), which is a collection of QA scripts in Python for monitoring the quality of the OpenTravelData data.

**Comment by alexprengere** [comment]
I just checked the latest file, the issue is fixed indeed.

The code I used is part of the [NeoBase test suite](https://github.com/alexprengere/neobase/blob/master/test_neobase.py#L37-L54). To create a Neobase instance from a specific optd file, you can either set the environment variable `OPTD_POR_FILE`, or use `NeoBase(open(filename))`.

Here is an extraction of those tests in an independant script that checks both timezones and geocodes.
```python
import pytz

def test_timezones(base):
    for por in base:
        tz = base.get(por, 'timezone')
        try:
            pytz.timezone(tz)
        except pytz.exceptions.UnknownTimeZoneError:
            print('Unknown timezone for {0} ({1})'.format(por, tz))


def test_geocodes(base):
    for por in base:
        if base.get_location(por) is None:
            print('Missing geocode for {0}'.format(por))


if __name__ == '__main__':
    from neobase import NeoBase
    test_timezones(NeoBase())
    test_geocodes(NeoBase())
```

You need to install the latest `pytz`, otherwise you might get false positives. Then run the tests with:
```bash
OPTD_POR_FILE=./optd_por_public.csv python test.py
```
