### ISSUE TITLE
Daylight savings?

### ISSUE THREAD

**Issue by thecodingdog** [opentraveldata/opentraveldata#79]
Not really an issue, but a question - is this file updated per changes in daylight savings? Thanks for providing this info!

**Comment by alexprengere** [comment]
The file is not updated according to daylight savings, but it is updated several times a week due to data updates.

You can use the *timezone* field and an appropriate library to handle daylight savings. In Python, if you use the timezone `Europe/Paris` of the point of reference `PAR`:

```python
>>> from datetime import datetime as dt
>>> import pytz
>>> in_paris = pytz.timezone('Europe/Paris').localize
>>> in_paris(dt(2017, 10, 30)) - in_paris(dt(2017, 10, 29))
datetime.timedelta(1, 3600)  # 1day + 1hour
```

As you can see in this example, `pytz` counted the extra hour of sleep we got end of october.
