### ISSUE TITLE
Wrong Validity dates on Dummy Airports

### ISSUE THREAD

**Issue by Beovulfo** [opentraveldata/opentraveldata#87]
Validity dates on the following dummy airports is making Apps to crash:
HDQ
XXX
ZZZ

How could we remove validity dates on these airports?

**Comment by denisarnaud** [comment]
The [opentraveldata/optd_por_no_longer_valid.csv file](https://github.com/opentraveldata/opentraveldata/blob/master/opentraveldata/optd_por_no_longer_valid.csv) is for POR which are no longer valid. Hence, by definition, any record in that file should have an end date for the validity period.

For HDQ and XXX, I have assigned them to [Stansted](http://www.geonames.org/2637052) and [Hassfurt](http://www.geonames.org/2909335) respectively.

But as the ZZZ IATA code is used for airports having no IATA code (but having an ICAO code)(as ZZZ is not used by IATA, and there was no reason it would be used by IATA), we can re-activate that record. A work around is to set an end date of validity (far) in the future. That may help your applications not to crash.

But please bear in mind that all the records in the [opentraveldata/optd_por_no_longer_valid.csv file](https://github.com/opentraveldata/opentraveldata/blob/master/opentraveldata/optd_por_no_longer_valid.csv) are no longer valid, by design. Hence, the ``envelope_id `` flag is not empty. Your applications should take that flag into account.

**Comment by denisarnaud** [comment]
> apparently some airlines are still using these airports as dummy

At least some airlines are using such "fictitious points" as mystery destinations, which are disclosed at the latest moment to their customers. Some customers are indeed booking trips to unknown destinations, and discover a few days or hours before departure where they are actually flying to.

* That may be the usage for XXX.
* For HDQ, it rather seems to specify the Headquarters of some company. Many generic company.
* And for ZZZ, it rather corresponds to the Greenwich time longitude (longitude 0.0, hence Zero, that is, Zulu): http://en.wikipedia.org/wiki/Coordinated_Universal_Time#Time_zones
