### ISSUE TITLE
Include callsign and country in airline data

### ISSUE THREAD

**Issue by vrampal** [opentraveldata/opentraveldata#96]
Please include callsign and country in the airline information.

A good source for this information is Wikidata.

See: https://gist.github.com/vrampal/aeb222a3be31f1bad7bf3f9654baabcc

Thanks,
Vincent

**Comment by denisarnaud** [comment]
Thanks Vincent for your contribution!

The call sign is already included, when known and documented. It corresponds to the "sign" (otherwise) language code in the ``alt_names`` field.

The generated data file is [opentraveldata/optd_airlines.csv](https://github.com/opentraveldata/opentraveldata/blob/master/opentraveldata/optd_airlines.csv).

For the country, as there are multi-national airlines, the airport bases are documented instead. When there are several bases, for instance with Lufthansa (LH/DLH), the IATA codes are separated by the equal sign ("="), for instance ``FRA=MUC`` in the case of Lufthansa.

So, do not hesitate to amend the manually curated files directly:
* [opentraveldata/optd_airline_best_known_so_far.csv](https://github.com/opentraveldata/opentraveldata/blob/master/opentraveldata/optd_airline_best_known_so_far.csv)
* [opentraveldata/optd_airline_no_longer_valid.csv](https://github.com/opentraveldata/opentraveldata/blob/master/opentraveldata/optd_airline_no_longer_valid.csv)
