### ISSUE TITLE
Latest revision of optd por file

### ISSUE THREAD

**Issue by alexprengere** [opentraveldata/opentraveldata#97]
Hello,
The latest revision of the optd por file changes quite a few things. From what I understand, the increase in size matches the inclusion of non-IATA point of references. I understand the rationale behind this change, but this also affects quite a few projects relying on the file (big size change, different scope).

It also broke NeoBase because of the high number of ZZZ IATA codes (there is a structure storing duplicates and that caused a memory error). I [fixed NeoBase](https://github.com/alexprengere/neobase/commit/470f63247848e9ad32310c77c235fc9430d0d711) by automatically discarding ZZZ por at load time.

Perhaps a smooth transition would be to generate two files, one "as usual", and one including non IATA point of references. Obviously this can be done client side by filtering ZZZ por, but I feel quite a few projects are going to have some difficulties with the transition.

On a side note, wouldn't it be better to leave the IATA code field empty when no IATA code? I fear someday ZZZ will be attributed.

**Comment by denisarnaud** [comment]
Thanks Alex for having brought up that topic!

> On a side note, wouldn't it be better to leave the IATA code field empty when no IATA code? I fear someday ZZZ will be attributed.

I would not believe that the ``ZZZ`` code would be attributed, as it seems reserved (and designate Greenwich time, which is also called "Zulu", hence the "Z").
Nevertheless, your idea is good, and as seen from above commits, all the scripts have now been adapted so as to keep empty IATA codes for POR not referenced by IATA. It should also ease the tasks of downstream projects in order to filter those POR out (if needed).

As for a potential transition period, I would rather avoid it, because many things which start as temporary eventually become permanent... And, besides you, nobody has complained so far. If that extension of the OPTD POR file triggers some issues downstream, it should not be difficult to fix, for instance, as you suggest, just by filtering out the non-IATA-referenced POR.

As for the extension of the scope, please note that we started to add non-IATA-referenced airports over two years ago. See issue #15 for more details. At the time, it was for airports not referenced by IATA but having an ICAO code, and which could appear in some flight schedules. So, adding today the POR referenced by UN/LOCODE is a mere extension of that feature. Agreed, it adds quite a few POR (90,000). But now that non-IATA-referenced POR keep their IATA code empty, the whole data are much cleaner than it used to be at the time of the "ZZZ" work around (ie, for the last two years). Again, thanks for that suggestion!

Feel free to re-open that issue if you find errors which I can fix.

**Comment by denisarnaud** [comment]
Reproducing the comment on [acb89e317bb513e96fe23d7](https://github.com/opentraveldata/opentraveldata/commit/acb89e317bb513e96fe23d75c3da43a73ed747f2#commitcomment-30198561):

> Actually this sorting was very useful because it ensured consistency in the sense that airports came always before cities, so logic based on that could just index by IATA code and discard duplicates to get airport information, which is almost always what you want in those cases. Now it needs to either re-sort beforehand, or write more code to handle duplicates.
Again, I understand that location types have no sense for non-IATA point of references, but perhaps the previous sort was just more practical, and I cannot a clear benefit changing it.

Ok, so now it breaks the backward compatibility with some "feature" (here, the airports appear before the cities; but please bear in mind that almost all the travel-related POR came after the cities: heliports, railway stations, ports). You win :)

Let us do how you suggest:
* ``optd_por_public.csv`` will be kept as before, without the POR not referenced by IATA
* A new file will be generated, say ``optd_por_public_all.csv``, containing all the POR being referenced by any international organization (IATA, ICAO, UN/LOCODE). Hence, ``optd_por_public.csv`` will be a subset of ``optd_por_public_all.csv``.

Would it suit you better?

**Comment by alexprengere** [comment]
Honestly you convinced me before regarding the generation of two files. It will just be a maintenance burden for you, and will add complexity to the project. I believe people can just filter out what they do not need (in my case, non-IATA por), or sort the output for their use case if necessary.

Regarding my comment on the sorting, what I suggested was to have a consistent sort for por sharing an IATA code, even if this sort is changed. That way people can somewhat rely on it, as I did before. The new sort based on GeoNames ID is harder to benefit from, from a programmer's point of view, IMHO.

To conclude, just reinstating the old sort (IATA then location type then GeoNames ID) looks like a good solution to me, but in the end I will update my integration script whatever you decide 😉

**Comment by denisarnaud** [comment]
Thanks!

Yes, indeed, it would be (slightly) more complex to maintain two files, but would be manageable. To be honest, the fact that no one else complained seems to show that either that file is not so much in use, or that that change did not disrupt their own downstream scripts (obviously, I prefer the latter!).

For the sorting, we could:
1. Have all the IATA-referenced POR be sorted like before (IATA code, then location type). But, again, please note that that sorting method is not very consistent, as some travel-related POR (eg, airports and bus stations) appear before cities, while some other POR appear after the city they serve (heliports, railway stations and ports). And there are in some cases several cities for the same IATA code (for instance, Raleigh and Durham for RDU or Basel/Mulhouse for EAP), and here the sorting was according to Geonames ID.
2. Have all the non-IATA-referenced POR sorted by Geonames ID only, and as a numeric values (before, they used to be sorted by text-value, which not very consistent).

I can introduce that two-fold sorting; it will be slightly more complex to process (as I have to split the file in two parts, sort them differently, and then to concatenate the results), but it is manageable.

In my opinion, the unique sort by IATA code and then by (numeric) Geonames ID is more consistent. But, as it somewhat breaks backward compatibility, I will do whatever you prefer.

Speaking about sorting POR, I still owe you #12. Don't worry, I don't forget :)

**Comment by tools4origins** [comment]
Hello,

I wouldn't be surprise that most users of the file use an offline version and they we're not impacted yet by the change but they may be when they'll update it,

I agree with Alex that maintaining a second file which would be a subset of the first would add an unnecessary complexity to the repository, what would you think of adding those non-IATA por in a separate file? Users who wants information about both could they just use both files?

**Comment by denisarnaud** [comment]
Ok, it is even easier to do. Let us to that.
Please that with respect to the sorting, I really believe that sorting on the location code is not that much consistent. But that is fine for me.

**Comment by alexprengere** [comment]
I agree with you on the sorting @denisarnaud. Sorting on the location code is just a poor proxy for "sort from more precise to less precise". What I would prefer is "put the city at the end", but I see no easy way to do this with `sort`, unless we start writing some code to implement some custom sort.

**Comment by denisarnaud** [comment]
> What I would prefer is "put the city at the end", but I see no easy way to do this with ``sort``

Well, there is "simple" way, but it is a little bit of a hack: at some point in the process, use ``Z`` for the location type of cities, sort on the location type, and then replace the ``Z`` character by ``C`` at the end of the process.

**Comment by denisarnaud** [comment]
Back to the old way to generate ``optd_por_public.csv``: that file contains only IATA-referenced POR, and the sorting is a) by IATA code then b) by location type and then c) by (numerical) Geonames ID.

There is a small difference with how it was before. Since ``optd_por_public.csv`` now contains only IATA-referenced POR, I no longer maintain the list of non-IATA-referenced POR which can nevertheless appear in some schedule files. In order to bring those POR back in ``optd_por_public.csv``, I would need to re-introduce the ``ZZZ`` work around.
If someone needs those POR back... then I would advise him/her to use the new ``optd_por_public_all.csv`` file, which contains all the POR which are referenced by any international organization, including IATA.

In the new ``optd_por_public_all.csv`` file, the sorting is a) by IATA code and then b) by numerical Geonames ID. No more sorting on location type in that new file. But I understand that none of the regular users so far will use that new file soon.

**Comment by denisarnaud** [comment]
> What I would prefer is "put the city at the end"

Done
